"""add created at field

Revision ID: 507a7b62dfb5
Revises: cfbb1d0bf0aa
Create Date: 2026-05-18 05:25:49.851132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507a7b62dfb5'
down_revision: Union[str, Sequence[str], None] = 'cfbb1d0bf0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
